name: Workflow Publisher
on:
 workflow_dispatch:
 push:
   branches: [ 'master']
   paths:
   - 'templates/**'
jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [ 'octokit.net' ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.OCTOKITBOT_PAT}}
      - name: Update workflows
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp ../main/templates/* .github/workflows/
        working-directory: ./${{ matrix.target_repo }}
      - name: Publish workflows
        shell: bash
        run: |
          git config --local user.email "octokit@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Github Agent | Workflow has updated"
          git push
        working-directory: ./${{ matrix.target_repo }}
