name: Workflow Publisher
on:
 workflow_dispatch:
 push:
   branches: [ 'master']
   paths:
   - 'templates/**'
jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: ['octokit-metrics']
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.OCTOKITBOT_PROJECT_ACTION_TOKEN}}
      - run: git checkout workflow-update || true
      - name: Update workflows
        shell: bash
        run: |
          ls
          mkdir -p ${{ matrix.target_repo }}/.github/workflows/
          cp main/.github/templates/* ${{ matrix.target_repo }}/.github/workflows/
        working-directory: ./
 
         
